import {defineArrayMember, defineField, defineType} from 'sanity'

const orderField = defineField({
  name: 'order',
  title: '显示顺序',
  type: 'number',
  initialValue: 0,
})

const enabledField = defineField({
  name: 'enabled',
  title: '在网站上显示',
  type: 'boolean',
  initialValue: true,
})

const slugField = defineField({
  name: 'slug',
  title: '网址编号',
  type: 'slug',
  options: {source: 'title', maxLength: 96},
  validation: (rule) => rule.required(),
})

const blockContent = defineType({
  name: 'blockContent',
  title: '正文',
  type: 'array',
  of: [defineArrayMember({type: 'block'})],
})

const siteSettings = defineType({
  name: 'siteSettings',
  title: '首页与网站设置',
  type: 'document',
  fields: [
    defineField({name: 'heroTitle', title: '首页主标题', type: 'string'}),
    defineField({name: 'heroSubtitle', title: '首页副标题', type: 'string'}),
    defineField({name: 'aboutDate', title: '关于我们日期', type: 'date'}),
    defineField({name: 'aboutTitle', title: '关于我们标题', type: 'string'}),
    defineField({
      name: 'aboutParagraphs',
      title: '关于我们正文',
      type: 'array',
      of: [defineArrayMember({type: 'text', rows: 4})],
    }),
    defineField({name: 'contactEmail', title: '联系邮箱', type: 'string'}),
    defineField({
      name: 'globalInterface',
      title: '全站导航与公共文字',
      type: 'object',
      fields: [
        defineField({name: 'brand', title: '网站标识文字', type: 'string'}),
        defineField({name: 'homeTitle', title: '首页浏览器标题', type: 'string'}),
        defineField({name: 'titleSuffix', title: '浏览器标题后缀', type: 'string'}),
        defineField({name: 'metaDescription', title: '网站搜索摘要', type: 'text', rows: 2}),
        defineField({name: 'continueLabel', title: '首页继续按钮', type: 'string'}),
        defineField({name: 'logoAlt', title: '首页标志替代文字', type: 'string'}),
        defineField({name: 'contactPrefix', title: '联系邮箱前缀', type: 'string'}),
        defineField({name: 'navHome', title: '导航：首页', type: 'string'}),
        defineField({name: 'navLearning', title: '导航：课程检索', type: 'string'}),
        defineField({name: 'navCourses', title: '导航：课程讲义', type: 'string'}),
        defineField({name: 'navResearch', title: '导航：科学研究', type: 'string'}),
        defineField({name: 'navVisualizations', title: '导航：可视化实验室', type: 'string'}),
        defineField({name: 'navPopsci', title: '导航：科普', type: 'string'}),
        defineField({name: 'navCommunity', title: '导航：科学社区', type: 'string'}),
        defineField({name: 'navTeam', title: '导航：团队', type: 'string'}),
        defineField({name: 'footerOwner', title: '页脚版权名称', type: 'string'}),
        defineField({name: 'footerFrameworkPrefix', title: '页脚框架说明', type: 'string'}),
        defineField({name: 'footerFrameworkName', title: '页脚框架名称', type: 'string'}),
      ],
    }),
    defineField({
      name: 'homeInterface',
      title: '首页界面文字',
      type: 'object',
      fields: [
        defineField({name: 'newsFallback', title: '无标题新闻名称', type: 'string'}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
      ],
    }),
    defineField({
      name: 'news',
      title: '首页新闻',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'date', title: '日期', type: 'date'}),
            defineField({name: 'title', title: '标题', type: 'string', validation: (rule) => rule.required()}),
            defineField({name: 'summary', title: '内容', type: 'text', rows: 3}),
          ],
          preview: {select: {title: 'title', subtitle: 'date'}},
        }),
      ],
    }),
  ],
  preview: {prepare: () => ({title: '首页与网站设置'})},
})

const pageSettings = defineType({
  name: 'pageSettings',
  title: '页面标题与说明',
  type: 'document',
  fields: [
    defineField({
      name: 'pageKey',
      title: '对应页面',
      type: 'string',
      hidden: true,
      readOnly: true,
      options: {
        list: [
          {title: '课程检索', value: 'learning'},
          {title: '课程讲义', value: 'courses'},
          {title: '科学研究', value: 'research'},
          {title: '可视化实验室', value: 'visualizations'},
          {title: '科普', value: 'popsci'},
          {title: '科学社区', value: 'community'},
          {title: '团队', value: 'team'},
        ],
        layout: 'dropdown',
      },
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'title', title: '大标题', type: 'string', validation: (rule) => rule.required()}),
    defineField({name: 'intro', title: '标题下方说明', type: 'text', rows: 3}),
    defineField({name: 'date', title: '可选日期', type: 'date'}),
    defineField({
      name: 'learningInterface',
      title: '课程检索页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'learning',
      fields: [
        defineField({name: 'searchLabel', title: '搜索框标题', type: 'string'}),
        defineField({name: 'searchPlaceholder', title: '搜索框提示', type: 'string'}),
        defineField({name: 'clearLabel', title: '清除按钮', type: 'string'}),
        defineField({name: 'loadingStatus', title: '课程载入提示', type: 'string'}),
        defineField({name: 'foundPrefix', title: '搜索结果数量前缀', type: 'string'}),
        defineField({name: 'countSuffix', title: '课程数量后缀', type: 'string'}),
        defineField({name: 'noResultsTitle', title: '无搜索结果标题', type: 'string'}),
        defineField({name: 'noResultsText', title: '无搜索结果说明', type: 'text', rows: 2}),
        defineField({name: 'unavailableText', title: '课程不可用提示', type: 'string'}),
        defineField({name: 'backLabel', title: '详情页返回按钮', type: 'string'}),
        defineField({name: 'stageLabel', title: '推荐阶段字段名', type: 'string'}),
        defineField({name: 'natureLabel', title: '课程性质字段名', type: 'string'}),
        defineField({name: 'hoursLabel', title: '建议学时字段名', type: 'string'}),
        defineField({name: 'summaryHeading', title: '课程简介标题', type: 'string'}),
        defineField({name: 'textbooksHeading', title: '教材标题', type: 'string'}),
        defineField({name: 'courseFallback', title: '无课程名称提示', type: 'string'}),
        defineField({name: 'summaryFallback', title: '无课程简介提示', type: 'string'}),
        defineField({name: 'textbookFallback', title: '无教材提示', type: 'string'}),
        defineField({name: 'authorFallback', title: '无作者版本提示', type: 'string'}),
        defineField({name: 'emptyValue', title: '空字段文字', type: 'string'}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
      ],
    }),
    defineField({
      name: 'coursesInterface',
      title: '课程讲义页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'courses',
      fields: [
        defineField({name: 'noticeTitle', title: '下载说明标题', type: 'string'}),
        defineField({name: 'noticeItems', title: '下载说明内容', type: 'array', of: [defineArrayMember({type: 'text', rows: 2})]}),
        defineField({name: 'foundationLabel', title: '基础课程分组名', type: 'string'}),
        defineField({name: 'coreLabel', title: '核心课程分组名', type: 'string'}),
        defineField({name: 'advancedLabel', title: '高阶课程分组名', type: 'string'}),
        defineField({name: 'emptySuffix', title: '空分组提示后缀', type: 'string'}),
        defineField({name: 'backLabel', title: '详情页返回按钮', type: 'string'}),
        defineField({name: 'introHeading', title: '讲义简介标题', type: 'string'}),
        defineField({name: 'outlineHeading', title: '课程大纲标题', type: 'string'}),
        defineField({name: 'feedbackHeading', title: '反馈标题', type: 'string'}),
        defineField({name: 'downloadHeading', title: '下载标题', type: 'string'}),
        defineField({name: 'summaryFallback', title: '无讲义简介提示', type: 'string'}),
        defineField({name: 'outlineFallback', title: '无大纲提示', type: 'string'}),
        defineField({name: 'fileFallback', title: '无文件提示', type: 'string'}),
        defineField({name: 'emptyValue', title: '空字段文字', type: 'string'}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
        defineField({name: 'pdfLabel', title: 'PDF 标签', type: 'string'}),
        defineField({name: 'unnamedLecture', title: '无标题讲义名称', type: 'string'}),
        defineField({name: 'coverSuffix', title: '封面替代文字后缀', type: 'string'}),
        defineField({name: 'downloadFileLabel', title: '默认下载按钮', type: 'string'}),
      ],
    }),
    defineField({
      name: 'researchInterface',
      title: '科学研究页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'research',
      fields: [
        defineField({name: 'topicsHeading', title: '专题内容标题', type: 'string'}),
        defineField({name: 'emptyText', title: '空分类提示', type: 'string'}),
        defineField({name: 'allLabel', title: '“全部”按钮', type: 'string'}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
        defineField({name: 'researchFallback', title: '无研究领域名称提示', type: 'string'}),
        defineField({name: 'unnamedTopic', title: '无标题专题名称', type: 'string'}),
        defineField({name: 'emptyValue', title: '空字段文字', type: 'string'}),
        defineField({name: 'backLabel', title: '详情页返回按钮', type: 'string'}),
        defineField({name: 'typeLabel', title: '类型字段名', type: 'string'}),
        defineField({name: 'authorLabel', title: '作者字段名', type: 'string'}),
        defineField({name: 'difficultyLabel', title: '难度字段名', type: 'string'}),
        defineField({name: 'updatedLabel', title: '更新字段名', type: 'string'}),
        defineField({name: 'tagsLabel', title: '标签字段名', type: 'string'}),
        defineField({name: 'bodyHeading', title: '正文标题', type: 'string'}),
        defineField({name: 'tagsHeading', title: '标签标题', type: 'string'}),
        defineField({name: 'filesHeading', title: '附件标题', type: 'string'}),
        defineField({name: 'openFileLabel', title: '打开附件按钮', type: 'string'}),
        defineField({name: 'bodyFallback', title: '无正文提示', type: 'string'}),
      ],
    }),
    defineField({
      name: 'visualizationsInterface',
      title: '可视化实验室页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'visualizations',
      fields: [
        defineField({name: 'previewPlaceholder', title: '无预览图提示', type: 'string'}),
        defineField({name: 'emptyText', title: '空分类提示', type: 'string'}),
        defineField({name: 'backLabel', title: '详情页返回按钮', type: 'string'}),
        defineField({name: 'domainLabel', title: '领域字段名', type: 'string'}),
        defineField({name: 'difficultyLabel', title: '难度字段名', type: 'string'}),
        defineField({name: 'authorLabel', title: '作者字段名', type: 'string'}),
        defineField({name: 'relatedCoursesLabel', title: '关联课程字段名', type: 'string'}),
        defineField({name: 'fullscreenLabel', title: '全屏按钮', type: 'string'}),
        defineField({name: 'openLabel', title: '独立打开按钮', type: 'string'}),
        defineField({name: 'instructionsHeading', title: '操作说明标题', type: 'string'}),
        defineField({name: 'principlesHeading', title: '物理原理标题', type: 'string'}),
        defineField({name: 'relatedHeading', title: '相关内容标题', type: 'string'}),
        defineField({name: 'relatedFallback', title: '无相关内容提示', type: 'string'}),
        defineField({name: 'allLabel', title: '“全部”按钮', type: 'string'}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
        defineField({name: 'previewSuffix', title: '预览图替代文字后缀', type: 'string'}),
        defineField({name: 'unnamedVisualization', title: '无标题可视化名称', type: 'string'}),
        defineField({name: 'emptyValue', title: '空字段文字', type: 'string'}),
      ],
    }),
    defineField({
      name: 'popsciInterface',
      title: '科普页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'popsci',
      fields: [
        defineField({name: 'noticeItems', title: '资源说明', type: 'array', of: [defineArrayMember({type: 'text', rows: 2})]}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
        defineField({name: 'coverSuffix', title: '封面替代文字后缀', type: 'string'}),
        defineField({name: 'pdfLabel', title: 'PDF 标签', type: 'string'}),
      ],
    }),
    defineField({
      name: 'communityInterface',
      title: '科学社区页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'community',
      fields: [
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
        defineField({name: 'emptyValue', title: '空字段文字', type: 'string'}),
        defineField({name: 'backLabel', title: '详情页返回按钮', type: 'string'}),
        defineField({name: 'typeLabel', title: '类型字段名', type: 'string'}),
        defineField({name: 'authorLabel', title: '作者字段名', type: 'string'}),
        defineField({name: 'dateLabel', title: '日期字段名', type: 'string'}),
        defineField({name: 'tagsLabel', title: '标签字段名', type: 'string'}),
        defineField({name: 'bodyHeading', title: '正文标题', type: 'string'}),
        defineField({name: 'tagsHeading', title: '标签标题', type: 'string'}),
        defineField({name: 'filesHeading', title: '附件标题', type: 'string'}),
        defineField({name: 'bodyFallback', title: '无正文提示', type: 'string'}),
      ],
    }),
    defineField({
      name: 'teamInterface',
      title: '团队页面文字',
      type: 'object',
      hidden: ({document}) => document?.pageKey !== 'team',
      fields: [
        defineField({name: 'cardsHeading', title: '成员卡片标题', type: 'string'}),
        defineField({name: 'avatarPrefix', title: '默认头像文字前缀', type: 'string'}),
        defineField({name: 'backLabel', title: '详情页返回按钮', type: 'string'}),
        defineField({name: 'bioHeading', title: '个人简介标题', type: 'string'}),
        defineField({name: 'educationHeading', title: '教育背景标题', type: 'string'}),
        defineField({name: 'researchHeading', title: '研究方向标题', type: 'string'}),
        defineField({name: 'contentHeading', title: '探星阁内容标题', type: 'string'}),
        defineField({name: 'emptyLinks', title: '无内容链接提示', type: 'string'}),
        defineField({name: 'loadError', title: '加载失败提示', type: 'string'}),
        defineField({name: 'emptyValue', title: '空字段文字', type: 'string'}),
        defineField({name: 'avatarSuffix', title: '头像替代文字后缀', type: 'string'}),
        defineField({name: 'viewContentLabel', title: '默认查看内容按钮', type: 'string'}),
      ],
    }),
  ],
  preview: {select: {title: 'title', subtitle: 'pageKey'}},
})

const course = defineType({
  name: 'course',
  title: '课程',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '课程名称', type: 'string', validation: (rule) => rule.required()}),
    slugField,
    defineField({name: 'stage', title: '推荐学习阶段', type: 'string'}),
    defineField({name: 'field', title: '课程类别缩写', type: 'string'}),
    defineField({name: 'nature', title: '课程性质', type: 'string'}),
    defineField({name: 'hours', title: '建议学时', type: 'string'}),
    defineField({name: 'summary', title: '课程简介', type: 'text', rows: 5}),
    defineField({
      name: 'prerequisites',
      title: '前置课程',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'followups',
      title: '后续衔接课程',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'textbooks',
      title: '推荐教材与参考书',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'title', title: '书名', type: 'string'}),
            defineField({name: 'author', title: '作者与版本', type: 'string'}),
          ],
          preview: {select: {title: 'title', subtitle: 'author'}},
        }),
      ],
    }),
  ],
  orderings: [{title: '网站显示顺序', name: 'orderAsc', by: [{field: 'order', direction: 'asc'}]}],
  preview: {select: {title: 'title', subtitle: 'stage'}},
})

const lectureNote = defineType({
  name: 'lectureNote',
  title: '课程讲义',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '讲义名称', type: 'string', validation: (rule) => rule.required()}),
    slugField,
    defineField({
      name: 'level',
      title: '课程层级',
      type: 'string',
      options: {list: ['基础课程', '核心课程', '高阶课程'], layout: 'radio'},
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'term', title: '学期或版本', type: 'string'}),
    defineField({name: 'language', title: '语言', type: 'string', initialValue: '中文'}),
    defineField({name: 'summary', title: '讲义简介', type: 'text', rows: 4}),
    defineField({name: 'cover', title: '上传封面', type: 'image', options: {hotspot: true}}),
    defineField({name: 'coverPath', title: '现有封面路径', type: 'string', description: '迁移旧资源时使用；新内容优先上传封面。'}),
    defineField({name: 'detailPath', title: '现有详情页路径', type: 'string'}),
    defineField({name: 'body', title: '详细介绍', type: 'blockContent'}),
    defineField({name: 'outlineIntro', title: '大纲前说明', type: 'text', rows: 3}),
    defineField({name: 'outline', title: '课程大纲', type: 'array', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'feedback', title: '勘误与反馈', type: 'blockContent'}),
    defineField({
      name: 'downloads',
      title: '讲义文件',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'label', title: '按钮文字', type: 'string'}),
            defineField({name: 'file', title: '上传文件', type: 'file'}),
            defineField({name: 'filePath', title: '现有文件路径', type: 'string'}),
          ],
          preview: {select: {title: 'label'}},
        }),
      ],
    }),
  ],
  orderings: [{title: '网站显示顺序', name: 'orderAsc', by: [{field: 'order', direction: 'asc'}]}],
  preview: {select: {title: 'title', subtitle: 'level', media: 'cover'}},
})

const researchDomain = defineType({
  name: 'researchDomain',
  title: '研究领域',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '领域名称', type: 'string', validation: (rule) => rule.required()}),
    defineField({name: 'code', title: '英文缩写', type: 'string', validation: (rule) => rule.required()}),
    defineField({name: 'key', title: '筛选编号', type: 'slug', options: {source: 'code'}, validation: (rule) => rule.required()}),
    defineField({name: 'description', title: '领域说明', type: 'text', rows: 3}),
  ],
  preview: {select: {title: 'title', subtitle: 'code'}},
})

const researchArticle = defineType({
  name: 'researchArticle',
  title: '研究专题',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '专题标题', type: 'string', validation: (rule) => rule.required()}),
    slugField,
    defineField({name: 'domain', title: '所属领域', type: 'reference', to: [{type: 'researchDomain'}], validation: (rule) => rule.required()}),
    defineField({name: 'summary', title: '摘要', type: 'text', rows: 4}),
    defineField({name: 'author', title: '作者', type: 'string'}),
    defineField({name: 'difficulty', title: '难度', type: 'string'}),
    defineField({name: 'updatedAtText', title: '更新说明', type: 'string'}),
    defineField({name: 'tags', title: '标签', type: 'array', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'body', title: '正文', type: 'blockContent'}),
    defineField({name: 'file', title: '上传附件', type: 'file'}),
    defineField({name: 'filePath', title: '现有附件路径', type: 'string'}),
    defineField({name: 'externalUrl', title: '外部链接', type: 'url'}),
  ],
  preview: {select: {title: 'title', subtitle: 'domain.code'}},
})

const popularScience = defineType({
  name: 'popularScience',
  title: '科普资源',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '标题', type: 'string', validation: (rule) => rule.required()}),
    slugField,
    defineField({name: 'category', title: '分类', type: 'string', validation: (rule) => rule.required()}),
    defineField({name: 'summary', title: '简介', type: 'text', rows: 3}),
    defineField({name: 'cover', title: '上传封面', type: 'image', options: {hotspot: true}}),
    defineField({name: 'coverPath', title: '现有封面路径', type: 'string'}),
    defineField({name: 'file', title: '上传 PDF', type: 'file'}),
    defineField({name: 'filePath', title: '现有 PDF 路径', type: 'string'}),
  ],
  preview: {select: {title: 'title', subtitle: 'category', media: 'cover'}},
})

const visualization = defineType({
  name: 'visualization',
  title: '可视化项目',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '项目名称', type: 'string', validation: (rule) => rule.required()}),
    slugField,
    defineField({name: 'domains', title: '研究领域标签', type: 'array', of: [defineArrayMember({type: 'reference', to: [{type: 'researchDomain'}]})]}),
    defineField({name: 'summary', title: '项目简介', type: 'text', rows: 4}),
    defineField({name: 'difficulty', title: '难度', type: 'string'}),
    defineField({name: 'author', title: '作者', type: 'string'}),
    defineField({name: 'relatedCourses', title: '关联课程', type: 'array', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'previewImage', title: '预览图', type: 'image', options: {hotspot: true}}),
    defineField({name: 'sitePath', title: '交互 HTML 路径', type: 'string', description: '例如 visualizations/demo-placeholder.html'}),
    defineField({name: 'externalUrl', title: '外部交互地址', type: 'url'}),
    defineField({name: 'instructions', title: '操作说明', type: 'blockContent'}),
    defineField({name: 'principles', title: '物理原理', type: 'blockContent'}),
    defineField({name: 'relatedText', title: '相关内容', type: 'blockContent'}),
  ],
  preview: {select: {title: 'title', subtitle: 'difficulty', media: 'previewImage'}},
})

const communityPost = defineType({
  name: 'communityPost',
  title: '社区内容',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'title', title: '标题', type: 'string', validation: (rule) => rule.required()}),
    slugField,
    defineField({name: 'section', title: '所属板块', type: 'string', options: {list: ['科研伙伴', '成长故事'], layout: 'radio'}, validation: (rule) => rule.required()}),
    defineField({name: 'summary', title: '摘要', type: 'text', rows: 4}),
    defineField({name: 'author', title: '作者', type: 'string'}),
    defineField({name: 'date', title: '日期', type: 'date'}),
    defineField({name: 'tags', title: '标签', type: 'array', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'body', title: '正文', type: 'blockContent'}),
    defineField({name: 'externalUrl', title: '外部链接', type: 'url'}),
  ],
  preview: {select: {title: 'title', subtitle: 'section'}},
})

const teamMember = defineType({
  name: 'teamMember',
  title: '团队成员',
  type: 'document',
  fields: [
    orderField,
    enabledField,
    defineField({name: 'name', title: '姓名', type: 'string', validation: (rule) => rule.required()}),
    defineField({name: 'slug', title: '网址编号', type: 'slug', options: {source: 'name'}, validation: (rule) => rule.required()}),
    defineField({name: 'role', title: '当前身份', type: 'string'}),
    defineField({name: 'summary', title: '卡片简介', type: 'text', rows: 3}),
    defineField({name: 'avatar', title: '头像', type: 'image', options: {hotspot: true}}),
    defineField({name: 'avatarPath', title: '现有头像路径', type: 'string'}),
    defineField({name: 'tags', title: '研究标签', type: 'array', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'bio', title: '个人简介', type: 'blockContent'}),
    defineField({name: 'education', title: '教育背景', type: 'blockContent'}),
    defineField({name: 'researchInterests', title: '研究方向', type: 'blockContent'}),
    defineField({
      name: 'contentLinks',
      title: '探星阁内容',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'label', title: '显示名称', type: 'string'}),
            defineField({name: 'url', title: '链接', type: 'string'}),
          ],
          preview: {select: {title: 'label', subtitle: 'url'}},
        }),
      ],
    }),
  ],
  orderings: [{title: '网站显示顺序', name: 'orderAsc', by: [{field: 'order', direction: 'asc'}]}],
  preview: {select: {title: 'name', subtitle: 'role', media: 'avatar'}},
})

export const schemaTypes = [
  blockContent,
  siteSettings,
  pageSettings,
  course,
  lectureNote,
  researchDomain,
  researchArticle,
  popularScience,
  visualization,
  communityPost,
  teamMember,
]
